SET FOREIGN_KEY_CHECKS=0;

-- DROP TABLE IF EXISTS `users`;
-- DROP TABLE IF EXISTS `roles`;
-- DROP TABLE IF EXISTS `users_roles`;


CREATE TABLE IF NOT EXISTS `customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `email` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS=1;


